---
- block:
    - name: Validar numero de Tarjetas de Red en la VM {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: VBoxManage showvminfo {{ vmname }} | grep NIC | grep -v disabled | wc -l
      register: vmoutputnicn
  become: true

- block:
    - set_fact:
        vmnicnum: "{{ vmoutputnicn.stdout | trim }}"

- block:
    - name: Remover Tarjeta(s) de Red en la VM {{ vmostype }} - {{ vmname }} en VirtuaBox.
      shell: |
      {% if 1 == vmnicnum %}
  become: true